[package]
name = "SysMon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
sysinfo = "0.30.11"
ratatui = "0.26.2"
crossterm = "0.25"